
stages:
  - build

make manylinux:
  stage: build
  image: quay.io/pypa/manylinux2010_x86_64
  before_script:
    - yum install -y opus-devel
    - /opt/python/cp36-cp36m/bin/pip install -U Cython==0.27.3
    - /opt/python/cp37-cp37m/bin/pip install -U Cython==0.27.3
  script:
    - /opt/python/cp36-cp36m/bin/python ./setup.py sdist bdist_egg bdist_wheel
    - /opt/python/cp37-cp37m/bin/python ./setup.py bdist_egg bdist_wheel
    - for whl in dist/*.whl; do auditwheel repair "$whl" --plat manylinux2010_x86_64 -w dist; done
  artifacts:
    paths:
      - dist
    expire_in: 30 days
